### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by tdestro**
causing problems when called from mpf_inv

### CODE REVIEW

**Comment by czurnieden** [comment]
That's one of the smallest problems, I'm afraid, but nevertheless: thanks a lot!

Development came to an abrupt halt when I worked at implementing a standard compliant rounding and had to find out, to my utter dismay, that I messed it up in the very beginning: I forgot to add the necessary three guard bits. _sigh_

I had a clear conscious about laying it down because I never thought that anybody would use it. Do you want to use it (assuming it works properly in the near future) or did you just stumble over it? If you actually want to use it, I _will_ sit down and make the basics work, that is, work at the TODO list from top to (near) bottom.

If the basics are working I will also get rid of all operations involving native floating points (doubles) (for CPUs without an FPU) and add a stripped down version of LibTomMath  to make it freestanding.

**Comment by tdestro** [comment]
Hello Christoph,

Libtomfloat was one of the few (only?) non-gpl libraries in c for these
types of things. I'm running on an embedded device (arm cortex m4f) (I
can't link in GNU stuff and it'd probably be too big anyway). I've taken
the original libtom and basically been cherry picking your code where I
require extra the functionality. I ran into the memory leak after patching
in your mpf_inv_newton function and other required files for that.

I'm actually using this to calculate the relative drift and the relative
offset between two clocks, respectively. 2 64bit monotonic timers (iphone)
over bluetooth le.

Anyhow, some of it is definitely going to be used but it will likely just
be that function and it's requirements. I tried to get the other function
you had in in mpf_inv to work--I couldn't seem to get that one to work, or
work as fast (I forget). Any known bugs with the code I'm using?

Tony

**Comment by tdestro** [comment]
Have you had a look at the Go Math / Big libraries?
https://golang.org/pkg/math/big/#pkg-overview

I almost attempted porting them to c for this project.

**Comment by czurnieden** [comment]
Hi, Tony,

don't know of any bugs from memory but I committed lastly in December 2015 and haven't touched it since. Not because of the forgotten guard bits--although that caused a long stream of curses, curses that would make an old midwife blush, I can tell you--it was simply just a lack of time. Work slows down, usually, towards the end of year so I have a good chance to get to work on it then.

I have a long weekend this weekend (he says hopefully, staring at the phone) to at least add the guard bits to get the rounding working and the basic functions (+,-,*,/), too. But I assume that is already a bit late for you?

Oh, BTW: I cannot use the Go lib. because it is BSD licensed. I want to keep LibTomFloat Public Domain (which isn't possible anymore, thanks to these §%/&§&/§%%§ copyright lobbyists) or as close to Public Domain as possible.

Also: please be aware that some functions depend on my own LibTomMath variation. I hope I have put comments regarding these dependencies everywhere where they are relevant but I'm not sure anymore.

**Comment by tdestro** [comment]
I generally dislike copyright entirely. If I release anything I'll be sure
to release it as public domain. I noticed some of the rounding code and had
to disable it/use the standard libtomfloat/math stuff anyway as new lib nano is c89 only. arm gcc throws a fit on env.h

Any changes you make will be merged in, but I was intending on boiling everything down to save space on this device, but I still have a lot of room left so that won't be for a while.

Tony

**Pull request merged**
